---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app reactive-resume
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/meta/components/gatus/external
  dependsOn:
    - name: crunchy-postgres-stores
      namespace: database
    - name: bitwarden-store
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/main/apps/self-hosted/reactive-resume/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: rr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  timeout: 5m
  wait: false
