---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name autobrr-secret
spec:
  target:
    name: *name
    template:
      data:
        # App
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
        # OIDC
        AUTOBRR__OIDC_ENABLED: "true"
        AUTOBRR__OIDC_ISSUER: "https://sso.${SECRET_DOMAIN}/application/o/autobrr/"
        AUTOBRR__OIDC_CLIENT_ID: "{{ .AUTOBRR_CLIENT_ID }}"
        AUTOBRR__OIDC_CLIENT_SECRET: "{{ .AUTOBRR_CLIENT_SECRET }}"
        AUTOBRR__OIDC_REDIRECT_URL: "https://autobrr.${SECRET_DOMAIN}/api/auth/oidc/callback"
        AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: "true"
        # Database
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: '{{ .dbname }}'
        AUTOBRR__POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        AUTOBRR__POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        AUTOBRR__POSTGRES_USER: '{{ .user }}'
        AUTOBRR__POSTGRES_PASS: '{{ .password }}'
  dataFrom:
  - extract:
      key: autobrr
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: bitwarden
  - extract:
      key: postgres-pguser-autobrr
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: crunchy-postgres
