---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name reactive-resume-secret
spec:
  target:
    name: *name
    template:
      data:
        # -- Printer (Chrome) --
        CHROME_TOKEN: '{{ .TOKEN }}'
        # -- Database (Postgres) --
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        # -- Auth --
        ACCESS_TOKEN_SECRET: '{{ .ACCESS_TOKEN_SECRET }}'
        REFRESH_TOKEN_SECRET: '{{ .REFRESH_TOKEN_SECRET }}'
        # -- Emails --
        MAIL_FROM: '{{ .SMTP_USER }}'
        SMTP_URL: 'smtp://{{ .SMTP_USER }}:{{ .SMTP_PASS }}@{{ .SMTP_HOST }}'
        # -- Storage (Minio) --
        STORAGE_ACCESS_KEY: '{{ .AWS_ACCESS_KEY_ID }}'
        STORAGE_SECRET_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
        # -- Email (Optional) --
        DISABLE_SIGNUPS: "false"
        DISABLE_EMAIL_AUTH: "false"
        # -- OpenID (Optional) --
        VITE_OPENID_NAME: Authentik
        OPENID_AUTHORIZATION_URL: "https://sso.${SECRET_DOMAIN}/application/o/authorize/"
        OPENID_CALLBACK_URL: https://rr.${SECRET_DOMAIN}/api/auth/openid/callback
        OPENID_CLIENT_ID: '{{ .RRESUME_CLIENT_ID }}'
        OPENID_CLIENT_SECRET: '{{ .RRESUME_CLIENT_SECRET }}'
        OPENID_ISSUER: "https://sso.${SECRET_DOMAIN}/application/o/rresume/"
        OPENID_SCOPE: profile email
        OPENID_TOKEN_URL: "https://sso.${SECRET_DOMAIN}/application/o/token/"
        OPENID_USER_INFO_URL: "https://sso.${SECRET_DOMAIN}/application/o/userinfo/"
  dataFrom:
  - extract:
      key: browserless-chrome
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: rresume
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: rresume-bucket
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: protonmail
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: postgres-pguser-rresume
    sourceRef:
      storeRef:
        name: crunchy-postgres
        kind: ClusterSecretStore
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name browserless-chrome-secret
spec:
  target:
    name: *name
    template:
      data:
        TOKEN: '{{ .TOKEN }}'
  dataFrom:
  - extract:
      key: browserless-chrome
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
