---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name ${CLUSTER}-headlamp-admin
spec:
  secretStoreRefs:
    - name: bitwarden
      kind: ClusterSecretStore
  selector:
    secret:
      name: headlamp-admin
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: *name
