---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  target:
    name: *name
    template:
      data:
        # App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "{{ .PAPERLESS_CLIENT_ID }}",
                        "secret": "{{ .PAPERLESS_CLIENT_SECRET }}",
                        "settings": {
                            "server_url": "https://sso.${SECRET_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
        # Database
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: '{{ index . "pgbouncer-port" }}'
        PAPERLESS_DBNAME: '{{ .dbname }}'
        PAPERLESS_DBHOST: '{{ index . "pgbouncer-host" }}'
        PAPERLESS_DBUSER: '{{ .user }}'
        PAPERLESS_DBPASS: '{{ .password }}'
        # Mail
        PAPERLESS_EMAIL_HOST: '{{ .SMTP_HOST }}'
        PAPERLESS_EMAIL_PORT: "587"
        PAPERLESS_EMAIL_USE_TLS: "true"
        PAPERLESS_EMAIL_USE_SSL: "true"
        PAPERLESS_EMAIL_HOST_USER: '{{ .SMTP_USER }}'
        PAPERLESS_EMAIL_HOST_PASSWORD: '{{ .SMTP_PASS }}'
        PAPERLESS_EMAIL_FROM: "paperless@${SECRET_DOMAIN}"
  dataFrom:
  - extract:
      key: paperless
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: protonmail
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: bitwarden
  - extract:
      key: postgres-pguser-paperless
    sourceRef:
      storeRef:
        name: crunchy-postgres
        kind: ClusterSecretStore
