---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name outline-secret
spec:
  target:
    name: *name
    template:
      data:
        # S3
        FILE_STORAGE: "s3"
        FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"
        AWS_REGION: main
        AWS_S3_FORCE_PATH_STYLE: "true"
        AWS_S3_UPLOAD_BUCKET_NAME: outline
        AWS_S3_UPLOAD_BUCKET_URL: "{{ .OUTLINE_AWS_BUCKET_URL }}"
        AWS_ACCESS_KEY_ID: "{{ .OUTLINE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .OUTLINE_AWS_SECRET_ACCESS_KEY }}"
        # App
        SECRET_KEY: "{{ .OUTLINE_SECRET_KEY }}"
        UTILS_SECRET: "{{ .OUTLINE_UTILS_SECRET }}"
        # Oidc
        OIDC_DISPLAY_NAME: Authentik
        OIDC_SCOPES: openid profile email
        OIDC_USERNAME_CLAIM: preferred_username
        FORCE_HTTPS: "true"
        OIDC_CLIENT_ID: "{{ .OUTLINE_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OUTLINE_CLIENT_SECRET }}"
        OIDC_AUTH_URI: "https://sso.${SECRET_DOMAIN}/application/o/authorize/"
        OIDC_TOKEN_URI: "https://sso.${SECRET_DOMAIN}/application/o/token/"
        OIDC_USERINFO_URI: "https://sso.${SECRET_DOMAIN}/application/o/userinfo/"
        # Database
        DATABASE_URL: 'postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}/{{ index . "dbname" }}'
        PGSSLMODE: require
        # Mail
        SMTP_HOST: '{{ .SMTP_HOST }}'
        SMTP_PORT: "587"
        SMTP_USERNAME: '{{ .SMTP_USER }}'
        SMTP_PASSWORD: '{{ .SMTP_PASS }}'
        SMTP_SECURE: "true"
        SMTP_FROM_EMAIL: "outline@${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: outline
      sourceRef:
         storeRef:
           kind: ClusterSecretStore
           name: bitwarden
    - extract:
        key: protonmail
      sourceRef:
         storeRef:
           kind: ClusterSecretStore
           name: bitwarden
    - extract:
        key: postgres-pguser-outline
      sourceRef:
         storeRef:
           kind: ClusterSecretStore
           name: crunchy-postgres
